language: node_js
node_js:
- '4'
- stable

notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change

deploy:
  provider: npm
  email: hello@trailsjs.io
  api_key:
    secure: ZWv2ODuYGC2O1F9WFLWBJnJ2KDh+B4BbdbPCORSZAjueAicoGtH4Bx6cYLFU/YCT16XePeeeImeTLAh8VIVnmAH9935pQ8UGOh9di9i2WLa0S+wBOjJp9gtmMSJam0y2+81xhM1w5X2H+N4lQkKozwdJsTl0wPHUQHyNDAE57GQgdYYOUoSY1XYP5kZDfooXd0BOBV6xmqMhX7APTeGuh1mLuD3HUUfYDrnoKgwEFwJGhK7VGD4V7142syyxaW+i5fCtBWp0mQznm8zXxK51VtZbSZjJm8lV1ZsA+1opxguLkCk7nEsXKUUU/IDgUpQOmTqibgWeipOs6+4bo+sJrcgh5uT6HLOl7pd+LjKE+2reapezDl2hf6n818pumjsE9J0Wxb20I433+Az7Vzm4e6dfBdWSs+9MV39RHtbAVDQ15xV3ClfyQEca2215hHAtPHlxEcpOFl1gucXux7vGmn3jH8KdiX4PpuVpzIWz2nnBzD43BBtPvb1tBFe1srx7R8gy5VgA+UDfbUeHzCSsUVXXIlknl8UNf0mKjtvAhPGE/VuDLCu4Fb/NwxzaVvujqnrrWvfz05uJMnJ6jhdiwzHngK1E1oDxHTpxXQoIqsjnwecs/+C9gBhB+FJ1yJ9jMbh/1MskAmzOvxeyRjBvmCy7GEP6i9jyUFhirjkQjGM=
  on:
    tags: true
    repo: trailsjs/trailpack-router
    all_branches: true
